config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :admins,
    path: 'admins',
    module: 'admin/admins'
  )
  devise_for(
    :customers,
    path: '/',
    module: 'public/customers'
  )
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # public側のルーティング

  scope module: :public do

  #homes_controller
  root to: 'homes#top'
  get 'homes/about'

  #items_controller
  resources :items, only:[:index, :show]

  #customers_controller
  get "customers/my_page", to: 'customers#show', as: :my_page_customers
  resource :customers, only:[:edit, :update] do
    collection do
      get   :unsubscribe_confirmation
      patch :unsubscribe
    end
  end

  #cart_items_controller
  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

  #orders_controller
  resources :orders, only:[:new, :index, :show, :create] do
    collection do
      post :confirm
      get  :thanks
    end
 end

 #addresses_controller
 resources :addresses, only:[:index, :edit, :create, :update, :destroy]
 end

 #admin側のルーティング

 namespace :admin do
   root to: 'homes#top' #homes_controller
   resources :items, except:[:destroy] #items_controller
   resources :genres, only:[:index, :create, :edit, :update] #genres_controller
   resources :customers, only:[:index, :show, :edit, :update] #customers_controller
   resources :orders, only:[:show, :update] #orders_controller
   resources :order_details, only:[:update] #order_details_controller
 end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  # バリデーション機能
  validates :name, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true

  def full_address
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  #バリデーション
  validates :amount, inclusion: { in: 1..5 }, allow_nil: true


  def add_tax_price
    (self.price * 1.1).round
  end

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, format: { with:  /\A\d{10,11}\z/ }
  validates :email, presence: true

end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { creditcard: 0, banktransfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }

  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :payment_method, presence: true

  has_many :details
  belongs_to :customer
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @genre = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <% if @item.errors.any? %>
     <%= @item.errors.count %> 件のエラーが発生しました
       <% @item.errors.full_messages.each do |message| %>
         <ul>
           <li><%= message %></li>
         </ul>
     <% end %>
   <% end %>
  <h2>商品新規登録</h2>
  <%= form_with model: @item, url: admin_item_path(@item.id), local: true do |f| %>
  <div class="form-group">
    <label for="item_image">商品画像</label>
    <%= f.attachment_field :image %>
  </div>
  <div class="form-group">
    <label for="item_name">商品名</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="item_introduction">商品説明</label>
    <%= f.text_area :introduction, class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="genre">ジャンル</label>
    <%= f.collection_select :genre_id, @genre,:id, :name, {include_blank: '~選択してください~'}, {class: 'form-control',required: true} %>
  </div>
  <div class="form-group">
    <label for="price">税抜価格</label>
    <%= f.text_field :price, class: "form-control"%>円
  </div>
  <div class="form-group">
    <label for="price">販売ステータス</label>
    <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, "販売停止", {value: :false, style: "display: inline-block;"} %>
  </div>
  <div class="form-group">
  <%= f.submit "変更を保存", class: "btn btn-sm btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h2>商品一覧</h2>
  <%= link_to "新規登録", new_admin_item_path, class: "btn btn-success btn-sm mb-3" %>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジヤンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td>
          <%= item.id %>
        </td>
        <td>
          <%=link_to item.name, admin_item_path(item.id) %>
        </td>
        <td>
          <%= item.price %>
        </td>
        <td>
          <%= item.genre.name %>
        </td>
        <% if item.is_active == true %>
        <td>販売中</td>
        <% else %>
        <td>販売停止</td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <% if @item.errors.any? %>
     <%= @item.errors.count %> 件のエラーが発生しました
       <% @item.errors.full_messages.each do |message| %>
         <ul>
           <li><%= message %></li>
         </ul>
     <% end %>
   <% end %>
  <h2>商品新規登録</h2>
  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
    <div class="form-group">
      <label for="item_image">商品画像</label>
      <%= f.attachment_field :image %>
    </div>
    <div class="form-group">
      <label for="item_name">商品名</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="item_introduction">商品説明</label>
      <%= f.text_area :introduction, class: "form-control"%>
    </div>
    <div class="form-group">
      <label for="genre">ジャンル</label>
      <%= f.collection_select :genre_id, @genre,:id, :name, {include_blank: '~選択してください~'}, {class: 'form-control', required: true} %>
    </div>
    <div class="form-group">
      <label for="price">税抜価格</label>
      <%= f.text_field :price, class: "form-control"%>円
    </div>
    <div class="form-group">
      <label for="price">販売ステータス</label>
      <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
      <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止", {value: :false, style: "display: inline-block;"} %>
    </div>
    <div class="form-group">
    <%= f.submit "新規登録", class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2>商品詳細</h2>
  <div class="row">
    <div class="col-md-4 mt-5">
       <%= attachment_image_tag @item, :image, size: "200x200", format: 'jpeg', fallback: 'no_image.jpg', class: "img-fluid" %>
    </div>
  <div class="col-md-8 mt-5">
    <div class="item-group mb-2 ">
      <label for="item-name",>商品名</label>
        <%= @item.name %></span>
      </div>
    <div class="item-group mb-2">
      <label for="item-introduction">商品説明</label>
        <%= @item.introduction %>
    </div>
    <div class="item-group mb-2">
      <labal for="item-genre">ジャンル</labal>
        <%= @item.genre.name %>
    </div>
    <div class="item-group mb-2">
      <label for="item-price">税込価格(税抜価格)</label>
        <%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>) 円
    </div>
    <div class="item-group mb-2">
      <label for="item-status">販売ステータス</label>
      <% if @item.is_active == true %>
        <%= "販売中" %>
      <% else %>
        <%= "販売停止中" %>
      <% end %>
    </div>
    <%= link_to "編集する",  edit_admin_item_path(@item.id), class: "btn btn-success btn-sm" %>
  </div>
  </div>
</div>