config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :admins,
    path: 'admins',
    module: 'admin/admins'
  )
  devise_for(
    :customers,
    path: '/',
    module: 'public/customers'
  )
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # public側のルーティング

  scope module: :public do

  #homes_controller
  root to: 'homes#top'
  get 'homes/about'

  #items_controller
  resources :items, only:[:index, :show]

  #customers_controller
  get "customers/my_page", to: 'customers#show', as: :my_page_customers
  resource :customers, only:[:edit, :update] do
    collection do
      get   :unsubscribe_confirmation
      patch :unsubscribe
    end
  end

  #cart_items_controller
  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

  #orders_controller
  resources :orders, only:[:new, :index, :show, :create] do
    collection do
      post :confirm
      get  :thanks
    end
 end

 #addresses_controller
 resources :addresses, only:[:index, :edit, :create, :update, :destroy]
 end

 #admin側のルーティング

 namespace :admin do
   root to: 'homes#top' #homes_controller
   resources :items, except:[:destroy] #items_controller
   resources :genres, only:[:index, :create, :edit, :update] #genres_controller
   resources :customers, only:[:index, :show, :edit, :update] #customers_controller
   resources :orders, only:[:show, :update] #orders_controller
   resources :order_details, only:[:update] #order_details_controller
 end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  # バリデーション機能
  validates :name, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true

  def full_address
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  #バリデーション
  validates :amount, inclusion: { in: 1..5 }, allow_nil: true


  def add_tax_price
    (self.price * 1.1).round
  end

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, format: { with:  /\A\d{10,11}\z/ }
  validates :email, presence: true

end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { creditcard: 0, banktransfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }

  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :payment_method, presence: true

  has_many :details
  belongs_to :customer
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to  admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
   <% if @customer.errors.any? %>
   <%= @customer.errors.count %> 件のエラーが発生しました
     <% @customer.errors.full_messages.each do |message| %>
     <ul>
      <li><%= message %></li>
    </ul>
     <% end %>
  <% end %>
  <div class="row">
    <p class="guide"><%= @customer.first_name + @customer.last_name %>さんの会員情報編集</p>
  </div>
  <div class="row">
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true do |f| %>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">会員ID</th>
        <th><%= @customer.id %></th>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">氏名</th>
        <td><%= f.text_field :first_name, class: "field" %></td>
        <td><%= f.text_field :last_name, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">フリガナ</th>
        <td><%= f.text_field :first_name_kana, class: "field" %></td>
        <td><%= f.text_field :last_name_kana, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">郵便番号</th>
        <td><%= f.text_field :postal_code, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">住所</th>
        <td><%= f.text_field :address, size: 46, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">電話番号</th>
        <td><%= f.text_field :telephone_number, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">メールアドレス</th>
        <td><%= f.text_field :email, class: "field" %></td>
      </tr>
    </table>
    <table class="admin-customer-edit-table">
      <tr>
        <th class="admin-customer-edit-th">会員ステータス</th>
        <td class="pr-3"><%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効", {value: :true} %>
        </td>
        <td><%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", {value: :false} %>
        </td>
      </tr>
    </table>
    <table>
      <tr>
        <th class="admin-customer-edit-th"></th>
        <td><%= f.submit "変更を保存", class: "btn btn-success btn-sm" %></td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <p class="guide">会員一覧</p>
  </div>
  <div class="row">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th>会員IDID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to  admin_customer_path(customer.id) do %>
              <%= customer.first_name %><%= customer.last_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active == true %>
              <div class="text-success"><%= "有効" %></div>
            <% else %>
              <div class="text-black-50"><%= "無効" %></div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class="row mt-3 d-flex justify-content-center">
      <div class="customer-index-pagenate">
        <%= paginate(@customers) %>
      </div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <p class="guide"><%= @customer.first_name + @customer.last_name %>さんの会員詳細</p>
  </div>
  <div class="row mt-2">
    <table>
      <tr>
        <th class="customer-show-th">会員ID</th>
        <td class="customew-show-td"><%= @customer.id %></td>
      </tr>
      <tr>
        <th class="customer-show-th">氏名</th>
        <td class="customer-show-th"><%= @customer.first_name + @customer.last_name %></td>
      </tr>
      <tr>
        <th class="customer-show-th">フリガナ</th>
        <td class="customew-show-td"><%= @customer.first_name_kana + @customer.last_name_kana %></td>
      </tr>
      <tr>
        <th class="customer-show-th">郵便番号</th>
        <td class="customew-show-td"><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th class="customer-show-th">住所</th>
        <td class="customew-show-td"><%= @customer.address %></td>
      </tr>
      <tr>
        <th class="customer-show-th">電話番号</th>
        <td class=customew-show-td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th class="customer-show-th">メールアドレス</th>
        <td class="customew-show-td"><%= @customer.email %></td>
      </tr>
      <tr>
        <th class="customer-show-th">会員ステータス</th>
        <td>
          <% if @customer.is_active == true %>
            <div class="text-success"><%= '有効' %></div>
          <% else %>
            <div class="text-black-50"><%= '無効' %></div>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row">
    <table>
      <tr>
        <th class="customer-show-th"></th>
        <td>
          <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success btn-sm" %>
          <%= link_to "注文履歴一覧を見る",  admin_root_path, class: "btn btn-primary btn-sm ml-3" %>
        </td>
      </tr>
    </table>
  </div>
</div>