config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :admins,
    path: 'admins',
    module: 'admin/admins'
  )
  devise_for(
    :customers,
    path: '/',
    module: 'public/customers'
  )
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # public側のルーティング

  scope module: :public do

  #homes_controller
  root to: 'homes#top'
  get 'homes/about'

  #items_controller
  resources :items, only:[:index, :show]

  #customers_controller
  get "customers/my_page", to: 'customers#show', as: :my_page_customers
  resource :customers, only:[:edit, :update] do
    collection do
      get   :unsubscribe_confirmation
      patch :unsubscribe
    end
  end

  #cart_items_controller
  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

  #orders_controller
  resources :orders, only:[:new, :index, :show, :create] do
    collection do
      post :confirm
      get  :thanks
    end
 end

 #addresses_controller
 resources :addresses, only:[:index, :edit, :create, :update, :destroy]
 end

 #admin側のルーティング

 namespace :admin do
   root to: 'homes#top' #homes_controller
   resources :items, except:[:destroy] #items_controller
   resources :genres, only:[:index, :create, :edit, :update] #genres_controller
   resources :customers, only:[:index, :show, :edit, :update] #customers_controller
   resources :orders, only:[:show, :update] #orders_controller
   resources :order_details, only:[:update] #order_details_controller
 end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  # バリデーション機能
  validates :name, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true

  def full_address
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  #バリデーション
  validates :amount, inclusion: { in: 1..5 }, allow_nil: true


  def add_tax_price
    (self.price * 1.1).round
  end

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, format: { with:  /\A\d{10,11}\z/ }
  validates :email, presence: true

end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { creditcard: 0, banktransfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }

  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :payment_method, presence: true

  has_many :details
  belongs_to :customer
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.details
    @postage = 800
  end

  def update
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <p class="guide">注文履歴詳細</p>
  </div>
  <div class="row">
    <table class="admin-orders-show-table">
      <tr>
        <th class="admin-orders-show-th">購入者</th>
        <td><%= link_to @order.customer.first_name + @order.customer.last_name, admin_customer_path(@order.id) %></td>
      </tr>
    </table>
  </div>
  <div class="row">
    <table class="admin-orders-show-table">
      <tr>
        <th class="admin-orders-show-th">注文日</th>
        <td><%= localize @order.created_at, format: :short %></td>
      </tr>
    </table>
  </div>
  <div class="row">
    <table class="admin-orders-show-table">
    <tr>
      <th class="admin-orders-show-th">配送先</th>
      <td>
        〒<%= @order.postal_code %>&ensp;<%= @order.address %>&ensp;
          <%= @order.name %>
      </td>
    </tr>
    </table class="admin-orders-show-table">
  </div>
  <div class="row">
    <table>
      <tr>
        <th class="admin-orders-show-th">支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
    </table>
  </div>
  <div class="row mt-4">
    <div class="col-md-6">
      <table class="table">
        <thead class="thead-light">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
        </thead>
        <tbody>
          <% @sum_price = 0 %>
          <% @order_details.each do |detail| %>
          <tr>
            <td><%= detail.item.name %></td>
            <td><%= detail.tax_included_price %></td>
            <td><%= detail.amount %></td>
            <td><%= detail.tax_included_price * detail.amount %></td>
            <% @sum_price += detail.tax_included_price * detail.amount %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 d-flex align-items-end ml-3">
      <table>
        <tr>
          <th class="admin-orders-show-th2">商品合計</th>
          <td><%= @sum_price %>円</td>
        </tr>
        <tr>
          <th class="admin-orders-show-th2">送料</th>
          <td><%= @postage %>円</td>
        </tr>
        <tr>
          <th class="admin-orders-show-th2">請求金額</th>
          <td><%= @sum_price + @postage %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>