config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :admins,
    path: 'admins',
    module: 'admin/admins'
  )
  devise_for(
    :customers,
    path: '/',
    module: 'public/customers'
  )
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # public側のルーティング

  scope module: :public do

  #homes_controller
  root to: 'homes#top'
  get 'homes/about'

  #items_controller
  resources :items, only:[:index, :show]

  #customers_controller
  get "customers/my_page", to: 'customers#show', as: :my_page_customers
  resource :customers, only:[:edit, :update] do
    collection do
      get   :unsubscribe_confirmation
      patch :unsubscribe
    end
  end

  #cart_items_controller
  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete :destroy_all
    end
  end

  #orders_controller
  resources :orders, only:[:new, :index, :show, :create] do
    collection do
      post :confirm
      get  :thanks
    end
 end

 #addresses_controller
 resources :addresses, only:[:index, :edit, :create, :update, :destroy]
 end

 #admin側のルーティング

 namespace :admin do
   root to: 'homes#top' #homes_controller
   resources :items, except:[:destroy] #items_controller
   resources :genres, only:[:index, :create, :edit, :update] #genres_controller
   resources :customers, only:[:index, :show, :edit, :update] #customers_controller
   resources :orders, only:[:show, :update] #orders_controller
   resources :order_details, only:[:update] #order_details_controller
 end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  # バリデーション機能
  validates :name, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true

  def full_address
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  #バリデーション
  validates :amount, inclusion: { in: 1..5 }, allow_nil: true


  def add_tax_price
    (self.price * 1.1).round
  end

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, format: { with:  /\A\d{10,11}\z/ }
  validates :email, presence: true

end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items
  has_many :details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { creditcard: 0, banktransfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }

  validates :total_payment, presence: true
  validates :address, presence: true
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :payment_method, presence: true

  has_many :details
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>nagano_cake</title>
  </head>

  <body>
    <header class="top-page-header">
      <div class="header-top-content">
        <%= link_to root_path, class: "header-title" do %>
          <div>NaganoCake</div>
            <div class="header-sub-title">~幸せのスイーツをあなたに~</div>
        <% end %>

        <div class="nav">
          <ul class="lists-right">
           <% if admin_signed_in? %>
           <li>
            <%= link_to "商品一覧", admin_items_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "会員一覧", admin_customers_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "注文履歴一覧", admin_root_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-lists" %>
          </li>
          <% elsif customer_signed_in? %>
           <li>
             <%= link_to "マイページ", my_page_customers_path, class: "nav-lists" %>
           </li>
           <li>
             <%= link_to "商品一覧", items_path, class: "nav-lists" %>
           </li>
           <li>
             <%= link_to "カート", cart_items_path, class: "nav-lists" %>
           </li>
           <li>
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-lists" %>
           </li>
          <% else %>
          <li>
            <%= link_to "About", homes_about_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "商品一覧", admin_items_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "新規登録", new_customer_registration_path, class: "nav-lists" %>
          </li>
          <li>
            <%= link_to "ログイン", new_customer_session_path, class: "nav-lists" %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="header-center">
      <div class="header-center-top">スイーツを買うなら</div>
      <div class="header-center-bottom">NaganoCake</div>
    </div>
    </header>

    <%= yield %>
  </body>
</html>